apiVersion: v1
data:
  .dockerconfigjson: {{- toYaml .Values.imageSecret | nindent 8 }}
kind: Secret
metadata:
  creationTimestamp: "2022-07-26T18:00:17Z"
  name: regcred
  labels:
    {{- include "torrentBotHelm.labels" . | nindent 4 }}
  resourceVersion: "114736"
  uid: 818454c2-2b77-4367-868a-946b306c02be
type: kubernetes.io/dockerconfigjson
