apiVersion: v1
data:
  .dockerconfigjson: {{- toYaml .Values.imageSecret | nindent 8 }}
kind: Secret
metadata:
  creationTimestamp: "2022-07-26T18:00:17Z"
  name: regcred
  labels:
    {{- include "torrentBotHelm.labels" . | nindent 4 }}
    
type: kubernetes.io/dockerconfigjson
