apiVersion: v1
data:
  botkey: {{- toYaml .Values.botkey | nindent 8 }}
kind: Secret
metadata:
  name: botsecret
  labels:
    {{- include "torrentBotHelm.labels" . | nindent 4 }}
  resourceVersion: "1"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque